export const VendorProducts = [
  {
    ProductName: "Smartphone XYZ",
    CurrentPrice: 12999,
    Mrp: 15999,
    Rating: "4.5 ★",
    Offer: "20% Off",
  },
  {
    ProductName: "Wireless Earbuds",
    CurrentPrice: 2499,
    Mrp: 2999,
    Rating: "4.2 ★",
    Offer: "15% Off",
  },
  {
    ProductName: "Laptop ABC",
    CurrentPrice: 54999,
    Mrp: 59999,
    Rating: "4.8 ★",
    Offer: "8% Off",
  },
  {
    ProductName: "Smartwatch DEF",
    CurrentPrice: 4999,
    Mrp: 5999,
    Rating: "4.3 ★",
    Offer: "17% Off",
  },
  {
    ProductName: "Gaming Headset",
    CurrentPrice: 3999,
    Mrp: 4599,
    Rating: "4.7 ★",
    Offer: "13% Off",
  },
];

export const categories = [
  {
    title: "Electronics",
    items: [
      "Mobile Phones",
      "Laptops",
      "Cameras",
      "Televisions",
      "Audio Devices",
      "Gaming Consoles",
      "Wearable Technology",
      "Accessories",
    ],
  },
  {
    title: "Clothing",
    items: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Footwear",
      "Winter Wear",
      "Activewear",
      "Traditional Wear",
      "Accessories",
    ],
  },
  {
    title: "Home & Kitchen",
    items: [
      "Furniture",
      "Home Decor",
      "Kitchen Appliances",
      "Cookware & Utensils",
      "Bedding",
      "Storage & Organization",
      "Lighting",
      "Cleaning Supplies",
    ],
  },
  {
    title: "Beauty",
    items: [
      "Skincare",
      "Makeup",
      "Hair Care",
      "Fragrances",
      "Bath & Body",
      "Men's Grooming",
      "Tools & Accessories",
      "Natural & Organic",
    ],
  },
  {
    title: "Health",
    items: [
      "Supplements",
      "Medical Equipment",
      "Health Monitors",
      "Personal Care",
      "First Aid",
      "Fitness Equipment",
      "Nutrition & Diet",
    ],
  },
  {
    title: "Books",
    items: [
      "Fiction",
      "Non-Fiction",
      "Educational",
      "Comics & Graphic Novels",
      "Children's Books",
      "Biographies",
      "Self-Help",
      "Cookbooks",
    ],
  },
  {
    title: "Toys",
    items: [
      "Action Figures",
      "Puzzles & Board Games",
      "Educational Toys",
      "Stuffed Animals",
      "Outdoor Play",
      "Building Sets",
      "Dolls & Accessories",
      "Vehicles & Remote-Control Toys",
    ],
  },
  {
    title: "Sports",
    items: [
      "Fitness Equipment",
      "Sports Apparel",
      "Footwear",
      "Outdoor Gear",
      "Team Sports Equipment",
      "Individual Sports Gear",
      "Accessories",
      "Water Sports",
    ],
  },
  {
    title: "Automotive",
    items: [
      "Car Accessories",
      "Motorcycle Accessories",
      "Car Electronics",
      "Tools & Equipment",
      "Tires & Wheels",
      "Oil & Fluids",
      "Exterior Care",
      "Interior Care",
    ],
  },
  {
    title: "Groceries",
    items: [
      "Fruits & Vegetables",
      "Snacks & Beverages",
      "Bakery Items",
      "Packaged Foods",
      "Dairy & Eggs",
      "Frozen Foods",
      "Meat & Seafood",
      "Organic Products",
    ],
  },
];
